# Generated by Django 3.2.5 on 2021-07-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinPrice', models.FloatField()),
                ('coinLink', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
